version: '3.7'
networks:
  routing:
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24
services:
  traefik:
    image: traefik:2.2.10
    restart: always
    container_name: reverse_proxy_traefik
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik.yml:/etc/traefik/traefik.yml
      - ./configs/dynamic:/etc/traefik/dynamic
    networks:
      routing:
        ipv4_address: 10.100.100.10
